'''
Task lists
'''
NETWORKING = {
    {
        'name':'networking problems',
        'tasklist':[
            'Wireless Network Shows Signal but wont Connect',
            'A Network Cable Is Unplugged',
            'IP Address Conflict (Address Already in Use)',
            'The Network Path Cannot Be Found',
            'Duplicate Name Exists on the Network',
            'Limited or No Connectivity',
            'Connected with Limited Access',
            'Unable to Join Network Failure (error -3)',
            'Unable to Establish the VPN Connection (error 800)',
            'Connection Problems',
            'Connection closed by remote host',
            'Connection refused',
            'Connection timed out',
            'Login incorrect',
            'The .netrc file not correct mode',
            'Network is unreachable',
            'Ruserok: permission denied',
            'Unknown host'
        ]
        },
    {
        'name':'Install well-functioning LAN/WAN',
        'tasklist':[]
        },
    {
        'name':'Manage IPV4',
        'tasklist':[
            'What is My IP Address?',
            'Configuring Your IP Address',
            'Enabling DHCP (Windows 10)',
            'Check Your Hosts File',
            'Create your own Internet Filter with the Windows Hosts file',
            'Check Your TCP/IP Settings',
            'Reset Your TCP/IP Manually',
            'Reset Your Winsock Manually',
            'IPv4 connectivity',
            'Domain Name System (DNS) name resolution for IPv4 addresses',
            'Network basic input/output system (NetBIOS) name resolution',
            'IPv4-based TCP sessions',
            'Arp',
            'Hostname',
            'Ipconfig',
            'Nbtstat',
            'Netsh',
            'Netstat',
            'Nslookup',
            'Ping',
            'Route',
            'Tracert',
            'Pathping',
            'SNMP service',
            'Event Viewer',
            'Performance Logs and Alerts',
            'Network Monitor',
            'Netdiag',
            'Telnet',
            'Ttcp',
            'Verify IPv4 connectivity',
            'Verify DNS name resolution for IPv4 addresses',
            'Verify NetBIOS name resolution.',
            'Verify IPv4-based TCP sessions.',
            'Repair the connection',
            'Verify configuration',
            'Manage configuration',
            'Verify reachability',
            'View and manage the IPv4 routing table',
            'Verify router reliability',
            'Check Packet Filtering',
            'TCP/IP filtering',
            'Verify Router Reliability',
            'Verifying DNS Name Resolution for IPv4 Addresses',
            'Verify DNS configuration',
            'Test DNS name resolution with the Ping tool',
            'Use the Nslookup tool to view DNS server responses',
            'Display and Flush the DNS Client Resolver Cache',
            'Test DNS Name Resolution with Ping',
            'Use the Nslookup Tool to View DNS Server Responses',
            'Verifying NetBIOS Name Resolution',
            'Verify NetBT configuration',
            'Test NetBIOS name resolution with Nbtstat',
            'Verify NetBIOS over TCP/IP configuration',
            'NetBIOS computer name',
            'NetBIOS node type',
            'Whether NetBIOS over TCP/IP is disabled',
            'Display the local NetBIOS name table',
            'Release and re-register the NetBIOS names of the node in WINS',
            'Display and Reload the NetBIOS Name Cache',
            'Test NetBIOS Name Resolution with Nbtstat',
            'Verifying IPv4-based TCP Sessions',
            'Verify TCP session establishment',
            'Verify NetBIOS sessions',
            'Check for Packet Filtering',
            'Verify TCP Session Establishment',
            'Another tool that you can use to test TCP connection establishment is Test TCP (Ttcp)',
            'Verify NetBIOS Sessions',
            'Troubleshoot IPv4 communications by verifying IPv4 connectivity,',
            'verifying DNS name resolution for IPv4 addresses,',
            'verifying NetBIOS name resolution,',
            'verifying IPv4-based TCP sessions.',
        ]
        },
    {
        'name':'Manage IPV6',
        'tasklist':[
            'Verify IPv6 connectivity.',
            'Verify DNS name resolution for IPv6 addresses.',
            'Verify IPv6-based TCP sessions.',
            'Verify configuration',
            'Manage configuration',
            'Verify reachability',
            'View and manage the IPv6 routing table'
            'Verify router reliability',
            'Check Packet Filtering',
            'The simple IPv6 firewall',
            'Internet Connection Firewall for IPv6',
            'Windows Firewall',
            'View and Manage the Local IPv6 Routing Table',
            'Verify Router Reliability',
            'Verifying DNS Name Resolution for IPv6 Addresses',
            'Verify DNS configuration',
            'Test DNS name resolution with the Ping tool',
            'Verify DNS Configuration',
            'Display and Flush the DNS Client Resolver Cache',
            'Test DNS Name Resolution with Ping',
            'Use the Nslookup Tool to View DNS Server Responses',
            'Verifying IPv6-based TCP Sessions',
            'Check for Packet Filtering',
            'Verify TCP Session Establishment',
            'Troubleshoot IPv6 communications by verifying IPv6 connectivity',
            'verifying DNS name resolution for IPv6 addresses',
            'verifying IPv6-based TCP sessions',
            'Address Resolution Protocol',
            'ARP',
            'ARP cache',
            'default gateway',
            'default route ',
            'default router',
            'destination cache',
            'DNS',
            'DNS client resolver cache',
            'DNS server',
            'Domain Name System (DNS)',
            'Host name',
            'Host name resolution',
            'Hosts file',
            'Lmhosts file',
            'negative cache entries',
            'neighbor cache',
            'NBNS',
            'NetBIOS name',
            'NetBIOS name cache',
            'NetBIOS name resolution',
            'NetBIOS name server (NBNS)',
            'routing table',
            'Windows Internet Name Service (WINS)'
        ]
        },
}
