# coding: utf8
'''
Task lists
'''
NETWORKING = [
    {
        'name':'Kindly assist in troubleshooting the following networking problems',
        'tasklist':[
            'Wireless Network Shows Signal but wont Connect',
            'A Network Cable Is Unplugged',
            'IP Address Conflict (Address Already in Use)',
            'The Network Path Cannot Be Found',
            'Duplicate Name Exists on the Network',
            'Limited or No Connectivity',
            'Connected with Limited Access',
            'Unable to Join Network Failure (error -3)',
            'Unable to Establish the VPN Connection (error 800)',
            'Connection Problems',
            'Connection closed by remote host',
            'Connection refused',
            'Connection timed out',
            'Login incorrect',
            'The .netrc file not correct mode',
            'Network is unreachable',
            'Ruserok: permission denied',
            'Unknown host'
        ]
        },
    {
        'name':'Im experiencing the following IPV4 issue',
        'tasklist':[
            'What is My IP Address?',
            'Configuring my IP Address',
            'Enabling DHCP (Windows 10)',
            'Check my Hosts File',
            'Create my own Internet Filter with the Windows Hosts file',
            'Check my TCP/IP Settings',
            'Reset my TCP/IP Manually',
            'Reset my Winsock Manually',
            'IPv4 connectivity',
            'Domain Name System (DNS) name resolution for IPv4 addresses',
            'Network basic input/output system (NetBIOS) name resolution',
            'IPv4-based TCP sessions',
            'Arp',
            'Hostname',
            'Ipconfig',
            'Nbtstat',
            'Netsh',
            'Netstat',
            'Nslookup',
            'Ping',
            'Route',
            'Tracert',
            'Pathping',
            'SNMP service',
            'Event Viewer',
            'Performance Logs and Alerts',
            'Network Monitor',
            'Netdiag',
            'Telnet',
            'Ttcp',
            'Verifying IPv4 connectivity',
            'Verifying DNS name resolution for IPv4 addresses',
            'Verifying NetBIOS name resolution.',
            'Verifying IPv4-based TCP sessions.',
            'Repairing the connection',
            'Verifying configuration',
            'Managing configuration',
            'Verify reachability',
            'Viewing and managing the IPv4 routing table',
            'Verifying router reliability',
            'Checking Packet Filtering',
            'TCP/IP filtering',
            'Verifying Router Reliability',
            'Verifying DNS Name Resolution for IPv4 Addresses',
            'Verifying DNS configuration',
            'Testing DNS name resolution with the Ping tool',
            'Using the Nslookup tool to view DNS server responses',
            'Displaying and Flushing the DNS Client Resolver Cache',
            'Testing DNS Name Resolution with Ping',
            'Using the Nslookup Tool to View DNS Server Responses',
            'Verifying NetBIOS Name Resolution',
            'Verifying NetBT configuration',
            'Testing NetBIOS name resolution with Nbtstat',
            'Verifying NetBIOS over TCP/IP configuration',
            'NetBIOS computer name',
            'NetBIOS node type',
            'Checking whether NetBIOS over TCP/IP is disabled',
            'Displaying the local NetBIOS name table',
            'Releasing and re-registering the NetBIOS names of the node in WINS',
            'Displaying and Reloading the NetBIOS Name Cache',
            'Testing NetBIOS Name Resolution with Nbtstat',
            'Verifying IPv4-based TCP Sessions',
            'Verifying TCP session establishment',
            'Verifying NetBIOS sessions',
            'Checking for Packet Filtering',
            'Verifying TCP Session Establishment',
            'Using Test TCP (Ttcp) test TCP connection establishment',
            'Verifying NetBIOS Sessions',
            'Troubleshooting IPv4 communications by verifying IPv4 connectivity,',
            'verifying DNS name resolution for IPv4 addresses,',
            'verifying NetBIOS name resolution,',
            'verifying IPv4-based TCP sessions.',
        ]
        },
    {
        'name':'Manage IPV6',
        'tasklist':[
            'Verifying IPv6 connectivity.',
            'Verifying DNS name resolution for IPv6 addresses.',
            'Verifying IPv6-based TCP sessions.',
            'Verifying configuration',
            'Managing configuration',
            'Verifying reachability',
            'Viewing and manage the IPv6 routing table'
            'Verifying router reliability',
            'Checking Packet Filtering',
            'The simple IPv6 firewall',
            'Internet Connection Firewall for IPv6',
            'Windows Firewall',
            'Viewing and Manage the Local IPv6 Routing Table',
            'Verifying Router Reliability',
            'Verifying DNS Name Resolution for IPv6 Addresses',
            'Verifying DNS configuration',
            'Testing DNS name resolution with the Ping tool',
            'Verifying DNS Configuration',
            'Displaying and Flushing the DNS Client Resolver Cache',
            'Testing DNS Name Resolution with Ping',
            'Using the Nslookup Tool to View DNS Server Responses',
            'Verifying IPv6-based TCP Sessions',
            'Checking for Packet Filtering',
            'Verifying TCP Session Establishment',
            'Troubleshooting IPv6 communications by verifying IPv6 connectivity',
            'verifying DNS name resolution for IPv6 addresses',
            'verifying IPv6-based TCP sessions',
            'Address Resolution Protocol',
            'ARP',
            'ARP cache',
            'default gateway',
            'default route ',
            'default router',
            'destination cache',
            'DNS',
            'DNS client resolver cache',
            'DNS server',
            'Domain Name System (DNS)',
            'Host name',
            'Host name resolution',
            'Hosts file',
            'Lmhosts file',
            'negative cache entries',
            'neighbor cache',
            'NBNS',
            'NetBIOS name',
            'NetBIOS name cache',
            'NetBIOS name resolution',
            'NetBIOS name server (NBNS)',
            'routing table',
            'Windows Internet Name Service (WINS)',
        ]
        },
]

def networking_list_length():
    l = []
    for i in NETWORKING:
        for j in i.values()[0]:
            l.append(j)

    return l