# coding: utf8
'''
SOFTWARE Task lists
'''
SOFTWARE = [
    {
        'name':'I would like to do the following outlook task',
        'tasklist':[
            'Create an e-mail signature in an Outlook',
            'Access AOL e-mail account with Outlook',
            'Undelete a message in an Outlook',
            'Purge deleted messages automatically in Outlook',
            'Switch to tasks in Outlook 2013',
            'Switch to mail in Outlook 2013',
            'In Outlook 2013, Disable in line reply in the reading panel',
            'Block any e-mail address in Outlook.com',
            'Change mail format in MS OUTLOOK',
            'Manage archive settings in Microsoft Outlook',
            'Create recurring meeting?',
            'Manage junk mails in MS Outlook',
            'Switch on to the next message',
            'Create An Address Book',
            'Customize The View Of My Mailboxes',
            'What Is Timeframe For Conversion',
            'Change The Font',
            'Where Is Mailboxes In Outlook',
            'How Much Mail Can Be Stored In Each Mailbox',
            'Determine How Much Space I’ve Used On The Exchange Server',
            'Delete Mail',
            'Setup A Group List',
            'Create Stationery',
            'Create A Signature',
            'Enable Automatic Spell Checking',
            'Configure The Google Directory So I Can Find Email Addresses'
            'Create Folders To Organize My Mail',
            'Search For Text Within A Message',
            'Set An Out Of Office Message',
            'Print Selected Text',
            'Clear The Search History',
            'Make Contacts Appear In The Address Book',
            'Prompt For Profiles',
            'Delete Ms Outlook Folders',
            'Export Outlook Folders To Another Format',
            'Back Up Outlooks Stuff',
            'Work With Your .pst File',
            'Export Outlook folders to another format',
            'Delete a .pst file from a profile',
            'Archive to avoid losing data',
            'Make contacts appear in the Address Book',
            'Clear the search history',
            'Print selected text',
            'Set an out of Office message',
            'Search for text within a message',
            'Create folders to organize my mail',
            'Configure the google directory so I can find email addresses',
            'Enable automatic spell checking',
            'Create a Signature',
            'Create Stationery?',
            'Setup a group list',
            'Determine how much space Ive used on the exchange server',
            'Change the font',
            'Customize the view of my mailboxes',
            'Create an address book',
            'Empty the trash and remove deleted items',
            'Set Up an Email Account',
            'Open Email Messages',
            'Reply to and Forward Email Messages',
            'Preview and Save an Attachment',
            'Print a Message',
            'Delete a Message',
            'Save a Message in an Alternate Format',
            'Delegate Access',
            'Customize the Navigation Pane',
            'Compose a Message',
            'Add an Attachment',
            'Add Voting Options to Messages',
            'Check Spelling and Grammar',
            'Format Text',
            'Use Microsoft Word to Edit Messages',
            'Insert a Hyperlink or Image in a Message',
            'Send a Message',
            'Change Your Calendar View',
            'Set Availability Status',
            'Print Your Schedule',
            'Schedule a Meeting',
            'Make Updates to Meetings',
            'Cancel a Meeting',
            'Reply to a Meeting Invitation',
            'Schedule an Appointment',
            'Make Updates to an Appointment',
            'Create Calendar Groups',
            'Delete a Calendar',
            'Work with Calendar Items',
            'Use Multiple Calendars',
            'Add a Contact',
            'Delete a Contact',
            'Import a Contact',
            'Print a Contact',
            'Update a Contact',
            'Updating a Contact',
            'Locate a Contact',
            'Sort Contacts',
            'Work with Contact Groups',
            'Manage Multiple Address Books',
            'Perform a Mail Merge'
        ]
        },
        {
            'name':'I would like to do the following microsoft world task',
            'tasklist':[
                'Connect with cloud service on word 2013',
                'Insert video in Microsoft Word 2013',
                'Collapse or expand parts of a document',
                'Edit PDF document in 2013',
                'Add foot-node & end note in word',
                'shortcut keys for creating hyperlink',
                'In MS word 2013 create a user entry forms',
                'In word 2013, insert a column break',
                'Delete a break in column',
                'Take a screen shot in word 2013',
                'Insert caption in your image',
                'Create a Macro in word 2013',
                'Create cross referencing in word 2013',
                'Restrict editing for someone in word 2013',
                'Insert an online picture in your word document in word 2013',
                'Customize the indent amount',
                'Short cut to move the insertion point to the beginning of the document',
                'Correct procedure for creating a hanging indent',
                'Create a custom watermark',
                'Short cut key to insert a page break',
                'Easiest way to save a chart so you can use it another document',
                'Add to label the values of individual chart elements',
                'Center Text',
                'Left Align Text',
                'Right Align Text',
                'Justify Text',
                'Font Color',
                'Double Space',
                'Indent Text',
                'Remove Indent',
                'Subscript',
                'Superscript',
                'Strikethrough',
                'Highlighter',
                'Remove Highlighter',
                'Add Page Top',
                'Add Page Bottom',
                'Remove Page',
                'Add Header',
                'Edit Header',
                'Remove Header',
                'Add Footer',
                'Edit Footer',
                'First Page Footer',
                'Odd/Even Footer',
                'Remove Footer',
                'Page Margins',
                'Portrait',
                'Landscape',
                'Show Ruler',
                'Hide Ruler',
                'Adding a Table of Contents',
                'Updating the Table of Contents',
                'Deleting the Table of Contents',
                'Footnotes and Endnotes',
                'Working with Footnotes',
                'Inserting Citations and a Bibliography',
                'Adding an Index',
                'Inserting a Table of Footnotes',
                'Insertinga Table of Authorities',
                'Updating a Table of Authorities',
                'Creating an Outline',
                'Adding Comments',
                'Tracking Changes',
                'Viewing Changes',
                'Viewing Additions',
                'Viewing Comments',
                'Viewing Markup',
                'Accepting Changes',
                'Rejecting Changes',
                'Comparing Documents',
                'Combining Documents',
                'Creating Envelopes and Labels',
                'Printing an Envelope',
                'Using Mail Merge',
                'Making Word Documents Read Only',
                'Password Protect Word Documents',
                'Removing Metadata from Files',
                'Restrict Formatting and Editing',
                'Using Bookmarks',
                'Adding Watermarks',
                'Adding Custom Watermarks',
                'Adding Titles to Sections',
                'Inserting Built-in Fields',
                'Using the Go To Feature',
                'Using Macros',
                'Customizing the Ribbon',
                'Preparing a Document for Internationalization and Accessibility',
                'Configuring Documents to Print',
                'Print a Document',
                'Adding Your Name to Microsoft Word',
                'Adding Values to Document Properties',
                'Working with Autosaved Version of Documents',
                'Adding Common Commands',
                'Adding Additional Commands with the Customize Dialog Box',
                'Adding Ribbon Commands or Groups',
                'Placement',
                'Customize the Quick Access Toolbar',
                'Selecting Text',
                'Selecting Fonts',
                'Working with Fonts',
                'Working with Lists',
                'Inserting a Hyperlink in a Document',
                'Using Styles',
                'Using Themes',
                'Applying and Creating Custom Styles',
                'Using the Ruler',
                'Using Tabs',
                'Setting Margins',
                'Find',
                'Find and Replace',
                'Appending Text to a Document',
                'Find and Replace Tips/Removing Blank Paragraphs',
                'Using the Clipboard',
                'Adding Page Numbers',
                'Using Headers and Footers',
                'Checking Spelling and Grammar',
                'Using Shading and Borders',
                'Setting Line and Paragraph Spacing',
                'Changing Styles',
                'Paragraph Marks and Other Formatting Symbols',
                'Using Formatting Symbols',
                'Insert a Table',
                'Adding Styles to a Table',
                'Formatting a Table',
                'Inserting Images',
                'Placing and Sizing Images',
                'Wrapping Text around an Image',
                'Adjusting Images',
                'Adding Borders and Effects to Images in Microsoft Word',
                'Orientation and Paper Size',
                'Changing the Page Setup',
                'Working with Fields',
                'Adding Page Breaks',
                'Adding Section Breaks',
                'Editing Charts',
                'Adding Charts',
                'Working with Clip Art',
                'Adding Shapes',
                'Working with SmartArt',
                'Creating Captions',
                'Building Blocks',
                'Inserting a Building Block',
                'Document Views',
                'Using the Navigation Pane',
                'Multiple Windows',
                'Working with Multiple Windows'

            ]
        },
        {
            'name':'I would like to do the following microsoft excel task',
            'tasklist':[
                'Creating a Workbook',
                'Saving a Workbook',
                'Adding Worksheets',
                'Deleting Worksheets',
                'Moving Worksheets',
                'Copying Worksheets',
                'Splitting the Worksheet Window',
                'Changing Worksheet Order',
                'Closing a Workbook',
                'On what tab are the following groups found: Sort & Filter, Zoom, Charts, Page Setup, Function Library, Number, Formula Auditing',
                'On what tabs and groups are the following commands found? Font Color, New Window, Sort, Trace Precedents, Wrap Text, Group, Print Area',
                'Opening a Workbook',
                'Printing Worksheets',
                'Adding Your Name to Microsoft Excel',
                'Managing Workbook Versions',
                'Adding Common Commands',
                'Adding Additional Commands with the Customize Dialog Box',
                'Adding Ribbon Commands or Groups',
                'Placement',
                'Remove Find from the Quick Access Toolbar',
                'Move the Quick Access Toolbar below the Ribbon',
                'Add color to workbook tabs',
                'Add themes to worksheets',
                'Add bold to text',
                'Add italics to text',
                'Add nderlining to text',
                'Add borders to cells',
                'Change text and cell colors',
                'Change the font and font size',
                'Align text',
                'Wrap text',
                'Indent text',
                'Merge and center text',
                'Change number formats',
                'Change date formats',
                'Show decimals',
                'Apply a theme of your choice to your workbook',
                'Selecting Ranges of Cells',
                'Hiding Worksheets',
                'Adding Color to Worksheet Tabs',
                'Adding Themes to Workbooks',
                'Adding a Watermark',
                'Working with Font Group Commands',
                'The Alignment Group',
                'The Number Group',
                'The simplest (not always the easiest) way to enter a formuar',
                'To quickly sum a row or column of data:',
                'To quickly count the number of cells in a row or column that have data:',
                'To quickly average the numbers in a row or column:',
                'To quickly find the minimum number in a row or column:',
                'To quickly find the maximum number in a row or column:',
                'Formulas can be copied from one cell to other cells in Excel. To copy formulas in Excel:',
                'To use Autofill to copy formulas:',
                'if you wish to display the formula within its associated cell in a worksheet',
                'Inserting Rows and Columns',
                'Deleting Rows and Columns',
                'Transposing Rows and Columns',
                'Setting Row Height and Column Width',
                'Hiding and Unhiding Rows and Columns',
                'Freezing Panes',
                'Working with Rows and Columns',
                'To use the Find command:',
                'To use the Replace command:',
                'To add a comment in Excel:',
                'To show or hide the text of a comment, select Show/Hide Comment. Show or Hide Comment',
                'To show the text of all comments, select Show All Comments.',
                'To insert a header or footer into a Microsoft Excel workbook:',
                'Using Named Ranges in Formulas',
                'Using Formulas That Span Multiple Worksheets',
                'Using the IF Function',
                'Using the PMT Function',
                'Using the LOOKUP Function',
                'Using the VLOOKUP Function',
                'Using the HLOOKUP Function',
                'Using the CONCATENATE Function',
                'Using the TRANSPOSE Function',
                'Using the PROPER, UPPER, and LOWER Functions',
                'Using the LEFT, RIGHT, and MID Functions',
                'Using Date Functions',
                'Using the YEAR, MONTH, and DAY Functions',
                'Creating Scenarios',
                'Rows and Columns as Lists',
                'Converting a List to a Table',
                'Removing Duplicates from a List',
                'Sorting Data in a List',
                'Filtering Data in a List',
                'Adding Subtotals to a List',
                'Working with Clip Art',
                'Using Shapes',
                'Working with SmartArt',
                'Visualizing Your Data',
                'Inserting Charts',
                'Editing Charts',
                'Add and Format Objects',
                'Create a Custom Chart Template',
                'Format Data as a Table',
                'Move between Tables and Ranges',
                'Modify Tables',
                'Define Tables',
                'Creating and Modifying a Table in Excel',
                'Applying Conditional Formatting',
                'Working with Styles',
                'Creating and Modifying Templates'
            ]
        },
        {
            'name':'',
            'tasklist':[
                'Adding Common Commands',
                'Adding More Commands with the Customize Dialog Box',
                'Adding Ribbon Commands or Groups',
                'To move the Quick Access Toolbar below the Ribbon:',
                'Getting Help',
                'Adding Your Name to Microsoft PowerPoint',
                'Pinning Favorites',
                'Selecting a Slide Layout',
                'Adding Text',
                'Editing Text',
                'Formatting Text',
                'Formatting Text as WordArt',
                'Creating Bulleted and Numbered Lists',
                'Formatting Text Placeholders',
                'Formatting Text into Columns',
                'Adding Slides to a Presentation',
                'Arranging Slides',
                'Adding Images to a Slide',
                'Inserting a Picture',
                'Inserting Clip Art',
                'Capturing and Inserting a Screenshot',
                'Editing an Image',
                'Formatting Images',
                'Applying a Style and Cropping an Image',
                'Grouping and Ungrouping Images',
                'Arranging Images',
                'Adding Shapes',
                'Inserting a Table',
                'Formatting Tables',
                'Importing Tables from External Sources',
                'Inserting a Chart',
                'Formatting a Chart',
                'Importing Charts from External Sources',
                'Checking Spelling',
                'Accessing Different Views of a Presentation',
                'Organizing a Presentation in Sections',
                'Adding Transitions to Slides',
                'Adding Speaker Notes',
                'Running a Slide Show',
                'Printing a Presentation'
            ]
        }
]

def software_list_length():
    l = []
    for i in SOFTWARE:
        for j in i.values()[0]:
            l.append(j)

    return l
