# coding: utf8
'''
Task lists
'''
SUPPORT = [
    {
        'name':'Develop training procedures',
        'tasklist':[
            'Wave - Add Employees',
            'Wave - Complete your Tax Profile',
            'Wave - Enter Payroll History',
            'Wave - Direct Deposit Application',
            'Wave - Enter Employee Hours',
            'Wave - Pay Your Employees!',
            'Wave - Receiving Your First Payment',
            'Wave - Receiving Deposit',
            'Wave - Receiving Deposits',
            'Wave - Changing Deposit Account',
            'Wave - Reconciling Invoices',
            'Wave - Pausing Payments by Wave',
            'Wave - Protecting your Business - Card Merchant Best Practices',
            'Zoho CRM - Add a Facebook Page',
            'Zoho CRM - Add a Twitter Handle',
            'Zoho CRM - Add a Google+ Page',
            'Zoho CRM - Remove Twitter/Facebook/Google+ Company Profile',
            'Zoho CRM - Enable Social Admin Permission',
            'Zoho CRM - Add a Lead/Contact from Facebook/Twitter/Google+',
            'Zoho CRM - Automate lead generation via social media',
            'Zoho CRM - Check the Activity Stream',
            'Zoho CRM - Add Keyword Tracking and Custom Streams for Twitter',
            'Zoho CRM - View Social Interactions',
            'Zoho CRM - Generate Web Forms',
            'Zoho CRM - Create Auto Response Rule',
            'Zoho CRM - Create Auto Response Rule Entry',
            'Zoho CRM - Enable Email Insights',
            'Zoho CRM - Monitor email response contextually',
            'Zoho CRM - How Zoho CRM tracks email activity',
            'Zoho CRM - Sort records by email status',
            'Zoho CRM - View email reports',
            'Zoho CRM - Email analytics',
            'Zoho CRM - Email and call analytics',
            'Zoho CRM - Sent Email status',
            'Zoho CRM - View email and call analytics',
            'Zoho CRM - Track email template performance',
            'Zoho CRM - Configure Gamescope Settings',
            'Zoho CRM - Filter records using advanced filters',
            'Zoho CRM - Use advanced filters effectively',
            'Zoho CRM - Filter records using Visitor Tracking information',
            'Zoho CRM - Enable CalDAV Access in Zoho CRM',
            'Zoho CRM - Configure CalDAV Account in an iOS Device',
            'Zoho CRM - Delete CalDAV Account',
            'Zoho CRM - View Trend Dashboards in Zoho CRM',
            'Zoho CRM - View Zia Notifications in Zoho CRM',
            'MailChimp - Set Up Your Account',
            'MailChimp - Work With Your List',
            'MailChimp - Customize Your Signup Form',
            'MailChimp - Create a Campaign',
            'MailChimp - View Your Campaign Reports',
            'MailChimp - Review Optional Advanced Features',
            'Dropbox - File backup and management-Dropbox',
            'Dropbox - private folder',
            'Dropbox - shared folder',
            'Dropbox - team folder',
            'Dropbox - Track team activity',
            'Dropbox - Overseeing team activity',
            'Dropbox - Create full report',
            'Dropbox - links a team member third-party app to their Dropbox account',
            'Dropbox - link a team member computer to their Dropbox account',
            'Dropbox - link a team member mobile device to their Dropbox account',
            'Dropbox - add member to the team',
            'Dropbox - removed member from the team',
            'Dropbox - Monitor your entire team by viewing specific events',
            'Dropbox - creating full reports across specific dates',
            'Dropbox - add more licenses to your plan',
            'Dropbox - view your current plan',
            'Dropbox - update billing information',
            'Dropbox - review billing history.',
            'Dropbox - Collaborate with the Dropbox Badge',
            'Dropbox - Joining a team',
            'Dropbox - Add comments on files',
            'Dropbox - Restoring a deleted file',
            'Dropbox - Add an extra layer of security',
            'Dropbox - To see how much space your entire team has used',
            'Dropbox - Adding computers to Dropbox',
            'Dropbox - File Revisions',
            'Dropbox - Account transfer',
            'Dropbox - Migrate data from a server',
            'Dropbox - Add your team files',
            'Dropbox - Set up your team folders',
            'Dropbox - Add tiered admins',
            'Dropbox - Invite your team',
            'Dropbox - Permanent file deletions',
            'Dropbox - Configure single sign-on',
            'Dropbox - Remote wipe',
            'Dropbox - Configure sharing settings',
            'Dropbox - Set folder permissions',
            'How to use Recuva to recover deleted files',
            'Recovering using recuva files from damaged or reformatted disks',
            'Online meetings-Skype',
            'Add a contact in Skype for Business',
            'Send an IM in Skype for Business',
            'Set up a Skype for Business meeting in Outlook',
            'Share your desktop or a program in Skype for Business',
            'Make and receive calls using Skype for Business',
            'Make and receive a Skype for Business video call',
            'Add a contact in Skype for Business',
            'Set up audio in Skype for Business',
            'Set up video in Skype for Business',
            'Make a call in Skype for Business',
            'Schedule a Skype for Business Meeting',
            'Join a Skype for Business Meeting',
            'Meet and share using Skype for Business',
            'Presence and IM in Skype for Business',
            'Outlook sync-AkrutoSync',
            'Configuring AkrutoSync to sync with your phone',
            'Configuring AkrutoSync to sync over the Internet',
            'AkrutoSync - Obtaining a DNS name from a third-party service No-IP.com',
            'AkrutoSync - Obtaining a DNS name from a third-party service DNSDynamic',
            'AkrutoSync - Obtaining a DNS name from a third-party service Two-DNS.de',
            'AkrutoSync - Other options for obtaining a DNS name other than from a third party',
            'Completing AkrutoSync setup to sync over the Internet',
            'Configuring AkrutoSync to sync over your home Wi-Fi network',
            'AkrutoSync - Configuring your firewall',
            'AkrutoSync - Starting a sync manually',
            'AkrutoSync - Synchronizing automatically',
            'AkrutoSync - Synchronizing Outlook Notes',
            'AkrutoSync - Synchronizing new data from phone to computer',
            'AkrutoSync - Synchronizing your phone with two or more computers',
            'Trello - Create A Board',
            'Trello - Add Lists',
            'Trello - Invite Members',
            'Trello - Setting privacy settings',
            'Trello - Create Cards From Email',
            'Trello - Mark Cards Done',
            'Trello - Import Items Instantly',
            'Trello - Team Visibility',
            'Trello - linking your Trello and Slack teams to foster seamless collaboration between the two apps',
            'Trello - Add Another Admin (Or Three)',
            'Trello - add new members to your team',
            'Trello - remove someone from the team',
            'Trello - Add Members to cards to assign people to tasks',
            'Trello - Add Checklists for cards that require subtasks',
            'Trello - Add a Due date to cards with deadlines',
            'Trello - Add Attachments',
            'Snagit - Panoramic Capture',
            'Snagit - Scrolling Capture',
            'Snagit - Save Capture Settings',
            'Snagit - Capture Text',
            'Snagit - Add Capture Info to Your Image',
            'Snagit - Create an Animated GIF',
            'Snagit - Working With Selection Tools',
            'Snagit - Using the Translation Workflow',
            'Social media management-Buffer and Hootsuite',
        ]
        },
    {
        'name':'Conduct office automation feasibility studies',
        'tasklist':[
            'Accounting and Invoicing-Wave',
            'Business templates and tools-SCORE',
            'CRM-Zoho CRM',
            'Diagramming-Draw.io',
            'Email marketing-MailChimp',
            'File backup and management-Dropbox',
            'File recovery-Recuva',
            'Online meetings-Skype',
            'Outlook sync-AkrutoSync',
            'Photo editor-PicMonkey',
            'Project management-Trello',
            'Scanner-TinyScan',
            'Screen capture-Snagit',
            'Time tracking-Chrometa',
            'Social media management-Buffer and Hootsuite',
        ]
        },
    {
        'name':'support task',
        'tasklist':[
            'Conduct workflow analysis',
            'Conduct space design',
            'Conduct cost comparison analysis',
            'Create desktop computing environment',
            'Initiate desktop computing environment',
            'Develop desktop computing environment'
        ]
        },
    {
        'name':'Providing procedural documentation',
        'tasklist':[
            'Accounting and Invoicing-Wave',
            'Business templates and tools-SCORE',
            'CRM-Zoho CRM',
            'Diagramming-Draw.io',
            'Email marketing-MailChimp',
            'File backup and management-Dropbox',
            'File recovery-Recuva',
            'Online meetings-Skype',
            'Outlook sync-AkrutoSync',
            'Photo editor-PicMonkey',
            'Project management-Trello',
            'Scanner-TinyScan',
            'Screen capture-Snagit',
            'Time tracking-Chrometa',
            'Social media management-Buffer and Hootsuite',
        ]
        },
]

def support_list_length():
    l = []
    for i in SUPPORT:
        for j in i.values()[0]:
            l.append(j)

    return l