# coding: utf8
'''
UNIX
'''

UNIX = [
    {
        'name':'UNIX Administration',
        'tasklist':[
            'Command not found',
            'Permission denied',
            'No route to host',
            'Connection refused',
            'Fix Linux booting problems',
            'When booting stalls',
            'Fix Linux driver problems',
            'Graphics hardware',
            'Wheres my desktop?',
            'Fix Linux wireless networking problems',
            'Double top',
            'Open a command prompt when issuing a command',
            'Find out how much memory Linux is using',
            'Change permissions under Linux',
            'Access partitions under Linux',
            'Switch from one desktop environment to another, such as switching from KDE to Gnome',
            'Contents in /usr/local',
            'Terminate an ongoing process',
            'Insert comments in the command line prompt',
            'Write a command that will look for files with an extension “c”, and has the occurrence of the string “apple” in it',
            'Write a command that will display all .txt files, including its individual permission',
            'Append one file to another in  Linux',
            'Find a file  using Terminal',
            'Create a folder using Terminal',
            'View the text file using Terminal',
            'Enable curl on Ubuntu LAMP stack',
            'Enable root loging in Ubuntu',
            'Run an Linux program in the background simultaneously when you start your Linux Server',
            'Uninstall the libraries in Linux',
            'During installation Linux creates a swap space partition. Why do I need this and how is it different from a Windows swap file',
            'During installation, I have a choice of creating swap space in a Primary or an Extended partition. Which should I choose',
            'How large a swap partition should I create',
            'How can I speed up performance by using multiple swap partitions',
            'How can I create multiple swap partitions on one or more drives',
            'How do I create a swap file in an existing Linux data partition',
            'I already have a large swap file in my Windows partition. Is there a way for Linux to use that swap space instead of creating another file',
            'How do I get Netscape for Linux to recognize my Netscape for Windows bookmark file',
            'How do I get my “winmodem” to work with Linux',
            'How can I tell how much memory Linux is using',
            'If Linux is not using all the memory I have installed, how do I make it use the rest',
            'I have a printer attached to the parallel port. What is this port called in Linux',
            'I have a device attached to a serial port. What is this port called in Linux',
            'What is my floppy drive called in Linux',
            'Wait a minute! Are you saying that there are no drive letters in Linux',
            'What about disk drive partitions? Don’t they have drive letters either',
            'Isn’t there a simpler way to access drives',
            'Is there an easy way to see what devices, such as drives, have been mounted',
            'Is there any way to change the default language used by the operating system and applications',
            'How do I format a floppy',
            'Is there online documentation for most programs',
            'How do I kill a program that has locked up',
            'Is there a way to increase the priority of a program to make it run faster',
            'Is there a spelling checker that I can use outside of a word processor',
            'My copy of Linux came with KDE and Gnome. Why do I need both',
            'I have both KDE and Gnome installed. How do I switch between them',
            'Can I add more desktop themes to use with Gnome and KDE',
            'How can I add programs to the Panel',
            'What is a virtual desktop',
            'You said I could have eight virtual desktops, but I see only four. Where are the rest',
            'Is it possible to share a program across multiple virtual desktops',
            'How can I change my desktop background color',
            'Is there a faster way to copy/cut & paste text than to use the pull-down menu',
            'If I want to issue a command, how do I open a command prompt',
            'What are the Linux equivalents to DOS/Windows commands',
            'How do I get help for command parameters',
            'How do I repeat a command',
            'What can I do if I don’t remember the name of a command I need',
            'I just used a command and got completely different results from the last time I used it. Why',
            'Long pathnames are a pain to type in. Is there any sort of shortcut I can use',
            'Is there a way to use one command to start more than one program at a time',
            'Is there a way to stack commands and have them execute concurrently in other command',
            'I can’t seem to log in, even though I’m using the correct password. What’s wrong',
            'Why do I need to use Shutdown? Can’t I just turn the power off',
            'I can find a Logout option, but where is Shutdown',
            'Is there a faster way to “warm-boot” the system than using Shutdown',
            'Do I have to use Shutdown if I am just turning over the system to another user',
            'I clicked on Logout and now the session is locked up. How do I log out',
            'How can I enable Linux to automatically restart applications that are running when I use',
            'What is the root directory',
            'Can you explain more how the directory structure of Linux works',
            'There are a number of directories I don’t recognize in the root directory. What are they',
            'Is there a command line shortcut to the login directory',
            'Some filenames are preceded by a dot. What does this mean',
            'When I look at a list of files and directories, the names are followed by something like -rw-rw-r-- or lrwxrwxrwx. What does this mean?',
            'The ls command doesn’t show everything in the directory. What’s wrong',
            'Can I use wildcard searches with the ls command, as I can with Dir in DOS/Windows',
            'I want to do a wildcard search on files with ? or * in the names. How do I do that',
            'How do I create or rename a file with special characters in the name',
            'How long can a filename be',
            'Is there a way to find files from a command shell',
            'Is there a way to browse through a text file from the command line',
            'Is there a command to search text files for a specific character string',
            'What are “symbolic” and hard links, and how can I identify them',
            'How do I create links',
            'How do I add users',
            'How do I delete users',
            'Is there any way to change a user ID',
            'Is there a way to disable a user account',
            'How do I add or change personal information in an account',
            'How do I add groups',
            'How do I add/delete users in a group',
            'How do I change a password',
            'What is a shadow password',
            'How do I display the permissions for a file or directory',
            'How do I change permissions'
        ]
    }
]

def unix_list_length():
    l = []
    for i in UNIX:
        for j in i.values()[0]:
            l.append(j)

    return l

