"""empty message

Revision ID: 110283ca7457
Revises: 9cf388d7cfb7
Create Date: 2018-01-10 15:58:17.432211

"""

# revision identifiers, used by Alembic.
revision = '110283ca7457'
down_revision = '9cf388d7cfb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('status', sa.String(length=255), nullable=True))
    op.add_column('assignedtasks', sa.Column('tries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignedtasks', 'tries')
    op.drop_column('assignedtasks', 'status')
    # ### end Alembic commands ###
