"""empty message

Revision ID: 37dad28f0fc3
Revises: 920c30c471c3
Create Date: 2018-02-01 18:15:56.458430

"""

# revision identifiers, used by Alembic.
revision = '37dad28f0fc3'
down_revision = '920c30c471c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('satisfaction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignedtasks', 'satisfaction')
    # ### end Alembic commands ###
