"""empty message

Revision ID: 3b8da1c180a2
Revises: 8e67b60cc1df
Create Date: 2018-03-13 17:29:27.459879

"""

# revision identifiers, used by Alembic.
revision = '3b8da1c180a2'
down_revision = '8e67b60cc1df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_description')
    # ### end Alembic commands ###
