"""empty message

Revision ID: 4c90ffbb2f43
Revises: None
Create Date: 2018-03-02 17:41:20.975988

"""

# revision identifiers, used by Alembic.
revision = '4c90ffbb2f43'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_firstname_key', 'users', type_='unique')
    op.drop_constraint(u'users_lastname_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_lastname_key', 'users', ['lastname'])
    op.create_unique_constraint(u'users_firstname_key', 'users', ['firstname'])
    # ### end Alembic commands ###
