"""empty message

Revision ID: 82db5170fb35
Revises: efa8edd6963d
Create Date: 2017-12-19 12:36:15.969700

"""

# revision identifiers, used by Alembic.
revision = '82db5170fb35'
down_revision = 'efa8edd6963d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assignedtasks', 'tasks', ['assignedtask_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('taskgroup', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'taskgroup')
    op.drop_constraint(None, 'assignedtasks', type_='foreignkey')
    # ### end Alembic commands ###
