"""empty message

Revision ID: 920c30c471c3
Revises: f0e3f23b9338
Create Date: 2018-02-01 17:12:00.452416

"""

# revision identifiers, used by Alembic.
revision = '920c30c471c3'
down_revision = 'f0e3f23b9338'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('date_opened', sa.DateTime(), nullable=True))
    op.add_column('assignedtasks', sa.Column('date_resolved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignedtasks', 'date_resolved')
    op.drop_column('assignedtasks', 'date_opened')
    # ### end Alembic commands ###
