"""empty message

Revision ID: 9cf388d7cfb7
Revises: af8594e9c3df
Create Date: 2018-01-06 16:07:21.090286

"""

# revision identifiers, used by Alembic.
revision = '9cf388d7cfb7'
down_revision = 'af8594e9c3df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'assignedtasks_assignedtask_id_fkey', 'assignedtasks', type_='foreignkey')
    op.drop_column('assignedtasks', 'assignedtask_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('assignedtask_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'assignedtasks_assignedtask_id_fkey', 'assignedtasks', 'tasks', ['assignedtask_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###
