"""empty message

Revision ID: a4ae01a7a9a6
Revises: 3b8da1c180a2
Create Date: 2018-03-27 16:12:44.467320

"""

# revision identifiers, used by Alembic.
revision = 'a4ae01a7a9a6'
down_revision = '3b8da1c180a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlydata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=True),
    sa.Column('avarage_time', sa.Integer(), nullable=True),
    sa.Column('avarage_quality', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('warnings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'warnings')
    op.drop_table('monthlydata')
    # ### end Alembic commands ###
