"""empty message

Revision ID: ade60247a554
Revises: 37dad28f0fc3
Create Date: 2018-02-19 18:25:32.132642

"""

# revision identifiers, used by Alembic.
revision = 'ade60247a554'
down_revision = '37dad28f0fc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('current_members', sa.Integer(), nullable=True),
    sa.Column('team_lead', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'group')
    op.drop_table('groups')
    # ### end Alembic commands ###
