"""empty message

Revision ID: af8594e9c3df
Revises: 82db5170fb35
Create Date: 2018-01-06 15:23:11.015945

"""

# revision identifiers, used by Alembic.
revision = 'af8594e9c3df'
down_revision = '82db5170fb35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('assignedtasks', sa.Column('group', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignedtasks', 'group')
    op.drop_column('assignedtasks', 'category')
    # ### end Alembic commands ###
