"""empty message

Revision ID: e29715270d1a
Revises: ade60247a554
Create Date: 2018-02-24 10:55:11.438421

"""

# revision identifiers, used by Alembic.
revision = 'e29715270d1a'
down_revision = 'ade60247a554'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('evaluate_comment', sa.String(length=2000), nullable=True))
    op.add_column('assignedtasks', sa.Column('evaluate_id', sa.Integer(), nullable=True))
    op.add_column('assignedtasks', sa.Column('evaluated_status', sa.String(length=255), nullable=True))
    op.drop_column('assignedtasks', 'tries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('tries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('assignedtasks', 'evaluated_status')
    op.drop_column('assignedtasks', 'evaluate_id')
    op.drop_column('assignedtasks', 'evaluate_comment')
    # ### end Alembic commands ###
