"""empty message

Revision ID: efa8edd6963d
Revises: ec68416dfc80
Create Date: 2017-12-13 16:23:07.820592

"""

# revision identifiers, used by Alembic.
revision = 'efa8edd6963d'
down_revision = 'ec68416dfc80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'users', ['firstname'])
    op.create_unique_constraint(None, 'users', ['lastname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
