"""empty message

Revision ID: f0e3f23b9338
Revises: 110283ca7457
Create Date: 2018-01-25 17:00:55.832573

"""

# revision identifiers, used by Alembic.
revision = 'f0e3f23b9338'
down_revision = '110283ca7457'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedtasks', sa.Column('user_answer', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignedtasks', 'user_answer')
    # ### end Alembic commands ###
