# coding: utf8
'''
Task lists
'''
SECURITY = [
    {
        'name':'Direct me on how to do the following task on HitmanPro',
        'tasklist':[
            'Configure HitmanPro',
            'Scan for threats',
            'Clean threats',
            'Add Files and Folders to the Whitelist',
            'Copy Whitelist Entries',
            'Ignore Whitelist Entries',
            'Delete Whitelist Entries',
            'Preview the Antimalware Health report',
        ]
        },{
        'name':'Direct me on how to do the following task on ESET NODE Antivirus',
        'tasklist':[
            'Get information about the protection status of ESET NOD32 Antivirus',
            'Configure scan',
            'launch a scan of your computer',
            'create a custom scan',
            'Display information about detection engine updates',
            'Provide access to Log files', 
            'Get protection statistics', 
            'Get watch activity', 
            'Adjust the security level for Computer',
            'Adjust the security level for Internet',
            'Scan all files for malicious code when they are opened, created, or run on your computer',
            'Monitor the events within the operating system',
            'Enable Gamer mode',
            'Disable Gamer mode',
            'Scan all traffic through HTTP or HTTPS for malicious software',
            'Monitors communication received through POP3 and IMAP protocol',
            'Filter websites suspected of distributing content intended to manipulate users into submitting confidential information',
            'Disable all antivirus and antispyware protection modules',
            'Enable kernel protection',
            'Strengthen protection against malware that has been designed to evade detection by antimalware products through the use of obfuscation or encryption ',
            'Fortify commonly exploited application types such as web browsers, PDF readers, email clients and MS Office components',
            'Filter by enabling operations with the exception of those blocked by pre-defined rules that protect your system',
            'Filter by notify the user about very suspicious events',
            'Filter by promting user to confirm operations',
            'Filter by blocking operations',
            'Filter by enabling operations and creating a rule after each operation',
            'Always allow loading selected drivers regardless of configured filtering mode, unless explicitly blocked by user rule',
            'Write all blocked operations to the HIPS log',
            'Displays a desktop notification each time an application is added to or removed from system startup',
            'Get Full access to a device',
            'Block Access to a device',
            'Only read access to the device',
            'Scan an inserted removable media device on-demand',
            'Specify scanning parameters such as scan targets and scanning methods',
            'launch a scan of removable media (such as CD/DVD/USB) that are currently connected to the computer',
            'launch the previously performed scan using the same settings it was run with',
            'Scan Microsoft Office documents before they are opened',
            'Scans files downloaded automatically by Internet Explorer such as Microsoft ActiveX elements',
            'Exclude files and folders from scanning',
            'Allow automatic system scans when your computer is not in use',
            'Configure monitoring for these standard protocols which are used by most Internet browsers',
            'Specify HTTP addresses to block, allow or exclude from checking',
            'Configure types of objects to scan (emails, archives, etc.)',
            'Configure detection methods for Web access protection etc',
            'Run Web access protection',
            'Run Anti-Phishing protection',
            'Check all JavaScript programs executed by internet browsers',
            'Creates a new list contain your own blacklist in addition to the predefined ones',
            'Modify existing lists',
            'Delete added lists',
            'Web access protection is enabled',
            'Toggle checking of received messages',
            'Toggle checking of sent messages',
            'Toggle checking of read messages',
            'Identify infected attachments, but will leave emails without taking any action',
            'Notify the user about infiltration(s) and delete the message',
            'Move infected emails automatically to the Deleted items folder',
            'Move infected emails automatically to the specified folder',
            'Specify the custom folder where you want to move infected emails when detected',
            'Toggle rescanning after a detection engine update',
            'Enable checking of email protocols',
            'Monitor all traffic through POP3for malicious software',
            'Get list of ports used by the POP3 protocol',
            'Ensure encrypted communication will not be checked',
            'Enable POP3S checking only for ports defined in Ports used by POP3S protocol',
            'Get a list of POP3S ports to check (995 by default)',
            'Disable protocol filtering',
            'Exclude specific applications from protocol filtering',
            'Exclude specific remote addresses from protocol filtering',
            'Exclude files and folders from scanning',
            'I you no longer want to use the secured browser for a site I have already saved',
            'Engage firewall to ensure network traffic is scanned in both directions',
            'Analyzes the content of network traffic and protects from network attacks',
            'Block any traffic that is considered harmful',
            'Detect and block communications associated with malicious command and control servers by recognizing patterns that indicate a computer is infected and a bot is attempting to communicate',
            'Protect computers from incoming network (Wi-Fi) threats',
            'Notifies you when a new device is detected on your network',
            'Build a custom configuration for your Firewall',
            'Block all unspecified connections by the Firewall',
            'Also evaluate rules from Windows firewall – In automatic mode, allow incoming traffic allowed by the Windows Firewall unless it has been blocked by Firewall rules',
            'Add rules and define how the Firewall handles network traffic',
            'Create zones containing one or multiple secure IP addresses',
            'Add IDS exceptions and customize reactions to malicious activities'
            'Configure advanced filtering options and the IDS functionality',
            'Allow or deny a specific service associated with a standard port number (HTTP – 80, POP3 – 110, etc.)',
            'Define actions for a certain computer or a group of networked computers',
            'Limit the number of rules that can be created for one application',
            'Scan network traffic in both directions',
            'Analyze the content of network traffic and protect from network attacks',
            'Block any traffic that is considered harmful',
            'Detect and block communications associated with malicious command and control servers by recognizing patterns that indicate a computer is infected and a bot is attempting to communicate',
            'Protect computers from incoming network (Wi-Fi) threats',
            'NNotify when a new device is detected on your network',
            'Ensure easy and convenient use of the firewall without the need to define rules'
            'Allow all outbound traffic for a given system and block most inbound traffic with the exception of some traffic from the Trusted Zone (as specified in IDS and advanced option/Allowed services) and responses to recent outbound communications',
            'Allow to build a custom configuration for Firewall',
            'Block all connections that are not defined by a specific rule that allows them',
            'This mode allows advanced users to define rules that permit only desired and secure connections',
            'Block all unspecified connections by the Firewall',
            'Allow incoming traffic allowed by the Windows Firewall unless it has been blocked by Firewall rules',
            'Use the firewall profile assigned to a connected network whenever possible',
            'Add a new network adapter',
            'Edit an existing network adapter',
            'Remove a network adapter from the list',
            'Display the Firewall rules window, where the list of all rules is displayed',
            'Add rules',
            'Edit rules',
            'Remove rules',
            'Configure rules',
            'Delete rules',
            'Adjust the priority level of a rule by selecting a rule(s) and clicking Top/Up/Down/Bottom',
            'Find a rule(s) by name',
            'Find a rule(s) by protocol',
            'Find a rule(s) by port',
            'Show if rules are enabled or disabled, the corresponding check box must be selected to activate a rule',
            'Show the protocol a rule is valid for',
            'Show the firewall profile a rule is valid for',
            'Show the status of communication (block/allow/ask)',
            'Show Direction of communication (incoming/outgoing/both)',
            'Show IP address and port of local computer',
            'Show IP address and port of remote computer',
            'SHow The application to which the rule applies',
            'Creates a new rule',
            'Edit existing rules',
            'Remove existing rules',
            'Specify a rule name, the direction of the connection, the action (Allow, Deny, Ask), the protocol and the profile to which the rule will apply',
            'Display information about the local side of the connection, including the number of the local port or port range and the name of the communicating application',
            'Get information about the remote port (port range)',
            'Define a list of remote IP addresses or zones for a given rule',
            'Add a predefined zone with range of IP addresses',
            'Add a created zone with range of IP addresses',
            'Record the activity connected with the rule will be recorded in a log',
            'Display a notification when the rule is applied',
            'Add A trusted zone representing a group of network addresses that are not blocked by the Firewall in any way',
            'Verify the network credibility of new networks that you are connecting to',
            'Configure known networks manually',
            'Shows if the network is set to Home or office network, Public or Use Windows setting',
            'Aapply created update profile when connected to this network',
            'Create a new known network',
            'Edit an existing known network',
            'Remove a selected nework from the list of known networks',
            'Adjust the priority level of known networks (networks are evaluated from top to bottom)',
            'Define the Network name and select the Protection type (Public network, Home or office network or Use Windows setting) for the network',
            'Use the Firewall profile drop-down menu to select the profile for this network',
            'If the network uses the Home or office network protection type, all directly connected network subnets are considered trusted',
            'Ensure successful authentication with the ESET Authentication Server take place',
            'Allow connections to trusted and known addresses',
            'Create a rule from the log',
            'Allow for the creation of new rules from the log',
            'See processes and applications that access your computer web camera'
            'Switche the firewall to an inactive state. See Network for more information',
            'Block all network traffic'
        ]
    },
]

def security_list_length():
    l = []
    for i in SECURITY:
        for j in i.values()[0]:
            l.append(j)

    return l
